# basic configs
data: WIKI_TALK  # dataset name
config: config/eval/APAN_lr_mod_large.yml  # path to config file
gpu: '0'  # which GPU to use
model_name: ''  # name of stored model
use_inductive: false
rand_edge_features: 32
rand_node_features: 0
eval_neg_samples: 1  # Note: changes test metric to AP+MRR
ratio: 0.5
epoch: 30
batch_size: -1
lr_scale: true
lr_scale_factor: 1.0
lr_scale_ceiling: 100.0

# neighbor sampler configs
chunk_num: 1
sampler_for_each_chunk: false
enable_pickle: false
cache_dir: sampler_caches
use_full_edge: false


# batch sampler configs: basic
mode: batch_stable_freezing_large  # baseline, batch_stable_freezing_large, batch_stable_freezing
node_count: 200 
window_size: 10
color_limit: -1
color_stack_per_node: 1
color_num_hops: 2


adaptive_node_count: log  # disable, linear, log
step_scale: 50
step_size: 0
minimum_scale_factor: 0.25
max_batch_size: 8000

observing: false
lr_scale: true
check_similarity: false
check_similarity_epoch: false
batch_freeze: false

cheat_code: disabled
ignore_stable: true
save_count: false

observe_batch_latency: false
observe_batch_utilization: false

# batch sampler configs: stable nodes
freeze_similarity: 0.95
freeze_any: true
freeze_window_size: 2

# extra_config: ''
# batch level output
batch_level_log: false
profile_stable: false
adaptive_update: false
adaptive_update_similarity: 0.9
adaptive_update_window_size: 2
adaptive_update_epoch: 1
